### ISSUE TITLE
Figure 1: Overview of type of data in the portal 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-paper-figures#1]
The first figure should encompass an overview of the portal and the contents in the portal. This should probably include the following: 

- [ ] Breakdown of the number of samples for each diagnosis. 
- [ ] Breakdown of how many samples of belong to each modality
- [ ] Breakdown of modalities by project - how many projects have bulk, CITE, spatial, etc. 

**How to display this information:**

I think there are a few ways we could show this information. Option 1 would be to just create a basic table where each unique diagnosis or modality is a separate row. If we went this route, we would probably want to create separate tables, so we have Table 1, Table 2, etc. 

Option 2 is to show this information visually. We could do a bar chart where each diagnosis is its own bar, and we show the total number next to the bar. This would mean we would have 50 bars, so we would want to make sure each of the diagnoses are legible. 
Alternatively, we could break this up by project and group the bars by project. However, that would probably get pretty busy since some diagnoses are found across multiple projects, so we would have > 50 bars. 
I did think about a stacked bar chart, where each bar is a project, but then we would need > 50 colors and that seems really bad. If there was a way we could label each part of the bar and have it be legible, that would be a better option than using a single color for each diagnosis. 

We could maybe group diagnosis by similar types (e.g. all blood cancers, all brain tumors, all sarcomas) and have a color for each group. Then we would need to show a larger more detailed table with all the diagnosis in the supplemental. 

**Other things we might include:**

Related to the breakdown of what's in the portal, I think it might be helpful to show an overview of the Portal. I wonder if we want our first figure to be the same as the about page figure and then we have the associated tables that will all get discussed in the same results section. I know we are updating the about page figure, so I'm not sure how that will affect using that here.

**Comment by allyhawkins** [comment]
Related to the first checkbox listed here, we want to have a figure that shows a summary of the different cancer types represented in the portal. At first I was worried that having a figure showing every diagnosis may be iffy, but I actually think I like it. I'm including two options for this panel below:

**Option 1:** 
Here I show all the different diagnoses that we have, ordered by number of samples. 
![no_groupings_disease_bar](https://github.com/AlexsLemonade/scpca-paper-figures/assets/54039191/714fe633-fc88-4933-90c3-a9fb571c659c)


**Option 2:**
For this option, I created some loose categories for different diagnoses. I took anything that has "leukemia" in it and labeled that as blood, "sarcoma" as sarcoma, etc. Then I faceted the bar chart based on those groups. I think I actually like this one. We would need to make sure we were explicit about how we categorize things, since right now I'm just doing some string detection to categorize so I definitely missed some. But this should give you an idea of what it would look like with different categories. 

![facet_groupings_disease_bar](https://github.com/AlexsLemonade/scpca-paper-figures/assets/54039191/d4edba38-14df-4099-9ec5-c0b37db8a0ec)

The other thing I tried, was to not facet but use the same plot as in Option 1 and color the bars by the category. I personally didn't think this was as clean as faceting, so if we like grouping diseases together, I think we should stick with faceting. 


**Additional sample metadata option:**
One question I have is if we want to try and summarize any other sample-level metadata. For example, we could include a stacked bar chart where for each disease we color the bars by the disease timing (I was inspired by OpenPBTA fig. 1B). For this, it would only make sense to include any diagnosis that we have n > 1. We would also want to summarize things so that anything with "initial diagnosis" gets that label, etc. I think this is helpful to see that for some diseases we have both initial diagnosis and recurrence samples. What do we think of including something like this? 
![image](https://github.com/AlexsLemonade/scpca-paper-figures/assets/54039191/9ada224c-6b8f-4dda-964f-59fe12cfc7cd)


Tagging @sjspielman @jaclyn-taroni and @jashapiro. Please let me know if you like either Option 1 or Option 2 better, if you have additional suggestions for the diagnosis bar chart, and if you think having a figure that shows disease timing would be useful or not worth it. Please let me know any comments by EOD Wednesday 12/20. 

Also I know the colors are bad, I'm refraining from editing those until we decide which format we like.

**Comment by sjspielman** [comment]
I like the faceted option better, and I do like the idea of showing the disease timings in the same figure! We can still probably order bars in each facet by overall frequency. I don't think we should _both_ count numbers at the top of bars and the grid, though since I think it's a bit too noisy with both. If we go with filling by timings, then I'd say stick with grid and no numbers. If we do not fill by timings, then use numbers and not grid.

A somewhat related question is if we want to establish a uniform palette to use throughout the paper for different cancer tissue groupings, ala OpenPBTA (but happily without a million groupings this time...). FYI though, there are quite a few brain cancers categorized as "other" in the plots above (PA, NB, MB, ATRT, etc.). I'm betting this code established the brain group via a regex for `glio`? If we do the faceting, we'll want to be sure we have the right groups all around. So, perhaps a separate issue to discuss out tissue groupings to facet by and optionally also choosing associated colors would be a good way to make sure we're on the same page for classifications.

**Comment by jashapiro** [comment]
I definitely favor faceting, but I might want the facet labels at the left side  ("under" the labels), which you should be able to do with `strip.position` in the `facet_` call and `theme(strip.placement="outside")`.

I _think_ I like the disease timings on the same plot, but it does get a bit busy. I like the category colors, but with 4 timings, it may be too much to use shades of those colors for the timings (I'd probably try to do it by making the colors pretty dark and then using alpha to lighten them, but as I said, I don't really expect it to work). 

I'm not sure why you say we would only include n > 1 for the disease timing plot? I feel like that is a separate decision: We might want to lump all diseases with n < x where x is some small number into an "Other" label (`forcats::lump_min()`)(still split by broad category for this plot).

I agree with @sjspielman on the grid options, though I would remove the horizontal gridlines no matter what. No need for those in a bar chart!

**Comment by jaclyn-taroni** [comment]
Given the number of diagnoses, I expect the color palette challenges to be _similar to OpenPBTA_. So, we should probably develop a palette fairly soon per @sjspielman's suggestion, and it should include higher-level groupings. 

People are going to be unhappy with me, but maybe (tasteful!) [`{ggpattern}`](https://coolbutuseless.github.io/package/ggpattern/) can help with including the disease timing information in the same plot.

I think we want the first figure to include the color palette we will use for grouping by diagnosis (or a higher-level) throughout the paper.

**Comment by jaclyn-taroni** [comment]
> We can definitely decide on a color palette that we like, but I don't imagine having any other figures where we are coloring by diagnosis? Or are you referring just to one color palette that gets used throughout the paper.

We may change our minds or be asked to do something in review, so best to get this out of the way, I think.

**Comment by jashapiro** [comment]
> > I'm not sure why you say we would only include n > 1 for the disease timing plot? I feel like that is a separate decision: We might want to lump all diseases with n < x where x is some small number into an "Other" label (forcats::lump_min())(still split by broad category for this plot).
> 
> In my original idea, we would have two separate plots. One that shows every single diagnosis and just the total count. The next plot would show the disease timing breakdown for any samples that we have multiple of. I was thinking it's more relevant to show samples where we may have multiple disease timings that people are able to look at and compare. Also I thought it would be really busy to have all diagnosis + disease timing. But it sounds like we want to do one single plot with total count + disease timing breakdown so then I wouldn't filter any diagnoses.

Either way, I think it probably still makes sense to have some lumping in the plot. We may want a supplemental table with all of the diseases included, but I don't think we need them all in the bar chart, and having an _Other_ label (broken up by grouping) would still be useful to reduce clutter.

**Comment by jaclyn-taroni** [comment]
@allyhawkins, I just wanted to give you a heads-up that I will probably drop some sketches into this issue today.

**Comment by jaclyn-taroni** [comment]
If we want to show every diagnosis and use patterns to represent disease timing, we would benefit from a layout and options that result in wider bars and make it easier to see the patterns over a variety of sample sizes. Here's a sketch I put together that also synthesizes some of what has already been discussed:

![scpca-figure-1-sketch](https://github.com/AlexsLemonade/scpca-paper-figures/assets/19534205/90a1b68f-bf4c-4c08-8b52-3e91984e48ca)

**Comment by allyhawkins** [comment]
Thanks for sketching this out. I like this approach! I had a few clarifying questions though: 

1. The 1... N on the x-axis are each a diagnosis right? So that each bar is a diagnosis? 
2. The legend will be black and white, but each panel will have bars that are different colors?

**Comment by jaclyn-taroni** [comment]
> I had a few clarifying questions though:
> 
> 1. The 1... N on the x-axis are each a diagnosis right? So that each bar is a diagnosis?
> 2. The legend will be black and white, but each panel will have bars that are different colors?

Yes, that's correct on both counts.

**Comment by allyhawkins** [comment]
Since we have separate issues for the other parts of this figure (see #14 and #15), I'm going to close this.
