### ISSUE TITLE
Decide on groupings for disease timing

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-paper-figures#11]
For figure 1, we will want to create stacked bar charts for the diagnoses. The stacked part of the bar chart will indicate the proportion of samples that belong to a specific disease timing. Before we can do that we will want to decide how to group all of the disease timings. 

I will post a table with the different disease timing options and then the group name so we can come to a consensus on how to label these.

**Comment by allyhawkins** [comment]
This one is a bit more complicated than the diagnosis groupings. I took all of the unique terms we use to refer to disease timing and grouped them into 6 groups + NA/Unknown. 

1. I wasn't entirely sure what to do with the few during treatment or post treatment resections. I created one group for `During or after treatment`? Along that same note, this whole group is part of the Collins lab and we have primary vs. mets as an additional column in the project metadata but not in the disease timing column. Do we want to use that information to group those samples instead? 
2. Do we want to separate out recurrence vs. metastasis? I just don't know how we really distinguish them from each other unless we were given that explicit information and we only have that for a few projects. The reason I didn't separate them here is because we have one that is a "metastatic recurrence". 
4. Do we want to distinguish NAs from Unknown? I would say yes, but it's going to get busy really fast. 
5. We also have a healthy sample. I still think we maybe don't want to include that in the main figure. 

Tagging @jaclyn-taroni @jashapiro @sjspielman for any thoughts on this. 

| disease_timing                                                                         	| group                       | 
| ----------------------------------------------------------------------------------------- | ---------------------------| 
| Local control surgery                                                                  	| During or after treatment |
| On therapy surgery                                                                     	| During or after treatment |
| Post treatment resection                                                               	| During or after treatment |
| Initial Diagnosis                                                                      	| Initial diagnosis | 
| Initial diagnosis                                                                      	| Initial diagnosis | 
| Initial diagnosis of 2nd primary RIG                                                   	| Initial diagnosis | 
| Initial diagnosis (prior needle biopsy)                                                	| Initial diagnosis | 
| Initial CNS tumor                                                                      	| Initial diagnosis | 
| Primary                                                                                	| Primary| 
| Autopsy                                                                                	| Post-mortem |
| Metastatic (autopsy)                                                                   	| Post-mortem |
| Deceased                                                                               	| Post-mortem |
| Progressive                                                                            	| Progressive |
| Progressive (Post-chemotherapy)                                                        	| Progressive |
| First recurrence after treatment for glioblastoma                                      	| Recurrence or metastasis |
| Recurrence as glioblastoma after multiple resections for pleomorphic xanthoastrocytoma 	| Recurrence or metastasis |
| Metastatic recurrence of anaplastic pleomorphic xanthoastrocytoma                      	| Recurrence or metastasis |
| Recurrence                                                                             	| Recurrence or metastasis |
| Metastatic resection                                                                   	| Recurrence or metastasis |
| Recurrence after treatment for retinoblastoma                                          	| Recurrence or metastasis |
| Metastasis                                                                             	| Recurrence or metastasis |
| NA                                                                                     	| |
| Healthy control                                                                        	| |
| Unknown                                                                                	| |

**Comment by allyhawkins** [comment]
A related thought after a slack discussion with Stephanie. What if we only categorize based on information that is actually relevant to the timing during which the sample was taken. Then we can have a separate supplemental plot that breaks down primary vs. mets for those samples where we have that information. To me, if a sample comes from a primary vs. met is a different question than _when_ during disease progression the sample was obtained. This would mean anything where we only have primary vs. met, the disease timing would be categorized as "Unknown" instead.

**Comment by jaclyn-taroni** [comment]
> What if we only categorize based on information that is actually relevant to the timing during which the sample was taken. Then we can have a separate supplemental plot that breaks down primary vs. mets for those samples where we have that information. To me, if a sample comes from a primary vs. met is a different question than _when_ during disease progression the sample was obtained. This would mean anything where we only have primary vs. met, the disease timing would be categorized as "Unknown" instead.

Agree with this.

**Comment by allyhawkins** [comment]
Okay I've done some re-grouping based on the idea that we will only use things that are relevant to the timing of when the sample was obtained. We will have an additional supplemental figure that contains the information for primary vs. mets. 

- Note that I included `NA` and `Unknown` both in the `Unknown` group. 
- Any samples where we only know about primary/met, are set to `Unknown` since we don't actually know when that sample was taken. 

| disease_timing                                                                         	| group                       | 
| ----------------------------------------------------------------------------------------- | ---------------------------| 
| Local control surgery                                                                  	| During or after treatment |
| On therapy surgery                                                                     	| During or after treatment |
| Post treatment resection                                                               	| During or after treatment |
| Initial Diagnosis                                                                      	| Initial diagnosis | 
| Initial diagnosis                                                                      	| Initial diagnosis | 
| Initial diagnosis of 2nd primary RIG                                                   	| Initial diagnosis | 
| Initial diagnosis (prior needle biopsy)                                                	| Initial diagnosis | 
| Initial CNS tumor                                                                      	| Initial diagnosis | 
| Autopsy                                                                                	| Post-mortem |
| Metastatic (autopsy)                                                                   	| Post-mortem |
| Deceased                                                                               	| Post-mortem |
| Progressive                                                                            	| Progressive |
| Progressive (Post-chemotherapy)                                                        	| Progressive |
| First recurrence after treatment for glioblastoma                                      	| Recurrence |
| Recurrence as glioblastoma after multiple resections for pleomorphic xanthoastrocytoma 	| Recurrence |
| Metastatic recurrence of anaplastic pleomorphic xanthoastrocytoma                      	| Recurrence |
| Recurrence                                                                             	| Recurrence |
| Recurrence after treatment for retinoblastoma                                          	| Recurrence |
| Primary                                                                                	| Unknown | 
| Metastatic resection                                                                   	| Unknown |
| Metastasis                                                                             	| Unknown |
| Unknown                                                                                	| Unknown |
| NA                                                                                     	| Unknown |
| Healthy control                                                                        	| Non-cancerous |

**Comment by jaclyn-taroni** [comment]
https://github.com/AlexsLemonade/scpca-paper-figures/issues/11#issuecomment-1865007924 LGTM

**Comment by allyhawkins** [comment]
I'm going to close this since it seems like we are all in agreement on the groupings.
