### ISSUE TITLE
Add some repo docs

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-paper-figures#19]
While reviewing #17, I thought it might be time to start documenting some items. The initial thoughts I had:

- It would be helpful to add to README something like: before getting started, run the script that grabs S3 data and enables running everything else (`op run -- Rscript scripts/figure_setup/sync-metadata.R`). 
- We also probably want to add some more info to the readme about which figures are which, like a bullet point list of contents.

**Comment by allyhawkins** [comment]
Thanks for filing this. I think this should be done after #13 goes in, so I'm adding that as a blocker.
