### ISSUE TITLE
Combine panels for supplemental Fig 2/3

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-paper-figures#47]
We will need to combine the panels for Supplemental Figure 2 and 3 (additional modalities figures) into a single file. The file should be letter size - 8.5 x 11.

**Comment by allyhawkins** [comment]
Fig S2 panels: 
A - CITE-seq workflow 
B - mini versions of the plots in the QC report related to ADT/CITE-seq data
C - multiplexed download 

Fig S3 panels: 
A - bulk workflow
B - spatial workflow 

At one point we discussed including illustrations of the associated downloads, but I think we might be okay without them.

**Comment by sjspielman** [comment]
> At one point we discussed including illustrations of the associated downloads, but I think we might be okay without them.

Is this referring to what you listed as Fig S2C? I don't see a multiplex download image in the repo

**Comment by allyhawkins** [comment]
> > At one point we discussed including illustrations of the associated downloads, but I think we might be okay without them.
> 
> Is this referring to what you listed as Fig S2C? I don't see a multiplex download image in the repo

Sorry, typo! I meant the multiplexed workflow.

**Comment by sjspielman** [comment]
@allyhawkins let me get your opinion on this - 

For FigS2, the ggplot panel is a bit domineering, but it's basically just what it is given the `aspect.ratio = 1` which we need for the UMAP panels. So I wondered if we might want to reorder be either: a/b are workflows and c is the plots, or a is the plots and b/c are workflows. _Conceptual_ screenshots below. Any thoughts?
 
<img src="https://github.com/AlexsLemonade/scpca-paper-figures/assets/4701111/9bed3322-a4f2-49d3-9ebc-635e7333808e" width="200"/>

<img src="https://github.com/AlexsLemonade/scpca-paper-figures/assets/4701111/b0a8d552-72e3-4a98-8a9d-7dcc531bbffe" width="180"/>

<img src="https://github.com/AlexsLemonade/scpca-paper-figures/assets/4701111/07625bb4-cdd9-495f-887b-61c1dd479260" width="180"/>

**Comment by sjspielman** [comment]
Ooof also, saved as an AI file it's about 47 MB - probably because of all the _points_ in the plots... Since this is a supplemental figure, maybe it's fine to just place a TIFF or PNG export of that ggplot panel in to reduce file size? We did this for some OpenPBTA supp figures that got too big.

**Comment by allyhawkins** [comment]
> For FigS2, the ggplot panel is a bit domineering, but it's basically just what it is given the aspect.ratio = 1 which we need for the UMAP panels. So I wondered if we might want to reorder be either: a/b are workflows and c is the plots, or a is the plots and b/c are workflows. Conceptual screenshots below. Any thoughts?

I think this will be partially dependent on the text, but I think for now we go with the second option where a) CITE seq workflow b) multiplexed workflow and c) mini plots. 

> Ooof also, saved as an AI file it's about 47 MB - probably because of all the points in the plots... Since this is a supplemental figure, maybe it's fine to just place a TIFF or PNG export of that ggplot panel in to reduce file size? We did this for some OpenPBTA supp figures that got too big.

I'm good with this, but we just won't be able to edit the font for that figure. If that's not important then thats fine.

**Comment by sjspielman** [comment]
> I'm good with this, but we just won't be able to edit the font for that figure. If that's not important then thats fine.

We can definitely edit it in R directly as needed!

**Comment by sjspielman** [comment]
Since we've been considering download images, I think Fig S3 might be a good place to put a few. There's plenty of space in an 8.5x11 page with only these two small workflows, and I think we could fit up to 3 download images easily.

**Comment by allyhawkins** [comment]
> Since we've been considering download images, I think Fig S3 might be a good place to put a few. There's plenty of space in an 8.5x11 page with only these two small workflows, and I think we could fit up to 3 download images easily.

I think if we wanted to include the spatial and the bulk download illustrations that's fine, but I wouldn't include anything else in that figure. I don't think it would make a ton of sense to be there. If we do that, we should probably include them elsewhere.

**Comment by sjspielman** [comment]
Closed by #55 and #61
