### ISSUE TITLE
Decide on tools to use for writing the manuscript

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-paper-figures#5]
Once we create the figures, we will need to decide on how we want to track writing the actual manuscript. We also will need a way to track references. 

Some options include: 

- Using [`manubot`](https://manubot.org/) for writing and tracking references. I know people have some opinions on this based on OpenPBTA, but I've never used this before. 
- Using google docs for writing plus one of the following plugins: 
  	- [Paperpile](https://paperpile.com/features/)
	- [Papers - smartCite for Google Docs](https://www.papersapp.com/smartcite-for-google-docs/#:~:text=In%20Google%20Docs%2C%20go%20to,appear%20in%20the%20right%20sidebar.) Jackie, Josh, and Ally all use Papers already, so we might want to try this first and then if it's bad we can always switch. 

My one concern with using google docs, is that I think it will be harder to track and review smaller changes in text. I personally find looking at the version history less straightforward in Google Docs vs a diff in git. But I'm sure there are also different headaches with Manubot.

**Comment by jashapiro** [comment]
I actually use Paperpile, not Papers, but I am not wedded to it.

I might generally favor `manubot`. With all internal authors, I think it will be fairly easy to handle, and the way it handles references is pretty nice. 

One other option you didn't mention though is `quarto`, which also handles references (via a bibtex file). One advantage of that is that we could keep the figure code in the same repo as well.

**Comment by sjspielman** [comment]
> One other option you didn't mention though is `quarto`, which also handles references (via a bibtex file).

Very straightforward CI for rendering the manuscript to a `gh-pages` branch, too:
- https://quarto.org/docs/publishing/ci.html
- https://github.com/quarto-dev/quarto-actions

**Comment by jaclyn-taroni** [comment]
`manubot` has the advantage of being something we've worked with before, and it's not that different from how we write documentation. `quarto` would have some learning curve of unknown steepness. I think a lot of the pain points associated with `manubot` use in the past would be resolved by having a project not being very long-lived or complicated – I wouldn't expect to need to upgrade versions mid-project or to run into problems like this https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/450 here.

I want to say this: we'll need to be very disciplined about how we do reviews if we're using any solution involving Git/GitHub. We will have problems if we have multiple reviewers per PR. Realistically, we'll need to get aligned up front, and then most people won't need to weigh in until near the end of the writing process after the methods are completed.

**Comment by sjspielman** [comment]
> I want to say this: we'll need to be very disciplined about how we do reviews if we're using any solution involving Git/GitHub

+1000000000

**Comment by allyhawkins** [comment]
We are going to go ahead and use Manubot for this one. Closing this out.
