### ISSUE TITLE
Figure 2B: Mini QC report plots

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-paper-figures#6]
After explaining the overview of the figure, I think it will be beneficial to include some plots that show each of the steps taken when processing each library. We include a lot of this in our main QC report. This figure should include an example of each of the following plots that are found in our QC report: 

- [ ] Knee plot showing which cells passed filtering out empty droplets 
- [ ] Summary of cell metrics showing the total umi/ number of genes/ mitochondrial content for each cell
- [ ] miQC model plot
- [ ] Plot showing removal of low quality cells (cells colored by keep/ remove)
- [ ] UMAP colored by number of genes detected OR do we show clusters...? Or both? 

To do this, we will need to find an example library that we like to use for re-creating each of these plots.

**Comment by jashapiro** [comment]
I wonder if we might include these in the overview figure as little illustrations? I'm not sure how much value there is in making these a separate figure. Another option might be an image of the QC report?

**Comment by allyhawkins** [comment]
Hmm... I like both of these ideas. I do think having an image would be hard to fit into one figure where it is legible. I think mini versions of the figures would be fun though and a nice way to show them.

**Comment by allyhawkins** [comment]
We have decided to include this with the overview of `scpca-nf` and be Fig. 2B. We will include mini versions of the plots in the QC report. We can do this by either shrinking the full size versions and making sure that the font size is still legible, or we can create dummy data with less points to make it easier to have smaller versions.
