### ISSUE TITLE
Update figure panels to show celltyping in processed object

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-paper-figures#63]
While writing legends, I realized that some of our workflow figures may not properly reflect the workflow. The [overview workflow](https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/figures/svgs/overview-scpca-fig2.svg) (Fig 2B) and all panels that stem from it make it look like cell type annotation is not included in the processed object. I would expect a cell type annotation arrow feeding into the `SCE Output Data` box, right?

The other panels that also use this base image are:

- [`additional-modalities-cite.svg`](https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/figures/svgs/additional-modalities-cite.svg) (Fig S2a, but note also #62)
- [`additional-modalities-multiplexed.svg`](https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/figures/svgs/additional-modalities-multiplexed.svg) (Fig S2b, but note also #62)

Tagging @allyhawkins @dvenprasad

**Comment by allyhawkins** [comment]
I think I have mixed feelings about this change. I think we talked about it when Deepa was putting these together and I'm not sure how you would show it unless you extended the line between the two arrows pointing down to the reports, but I'm not sure that really clears things up? 

I do want to note that we have a separate [cell type annotation workflow in Fig. 4](https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/figures/compiled_figures/pngs/figure_4.png) that shows cell types get incorporated into the processed object.

**Comment by sjspielman** [comment]
> I do want to note that we have a separate [cell type annotation workflow in Fig. 4](https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/figures/compiled_figures/pngs/figure_4.png) that shows cell types get incorporated into the processed object.

Yeah I did notice this!

I drafted up the _legend_ to emphasize that the cell type annotations are in the processed object, which may cover our bases if the design is too tricky with arrows? See: https://github.com/AlexsLemonade/ScPCA-manuscript/pull/36

**Comment by allyhawkins** [comment]
> I drafted up the legend to emphasize that the cell type annotations are in the processed object, which may cover our bases if the design is too tricky with arrows? See: https://github.com/AlexsLemonade/ScPCA-manuscript/pull/36

I think this is fine. Also in the section of the paper that refers to this figure we don't really talk about cell typing, just that we do it. There is a whole other section on cell typing and describing the cell type workflow that will come with Fig. 4, so my vote would be to leave it.
