### ISSUE TITLE
Add individual panel labels for Figure 2 QC report examples

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-paper-figures#66]
I was reviewing https://github.com/AlexsLemonade/ScPCA-manuscript/pull/36, and I agree with @sjspielman's comment:

> While writing this, I wondered whether we actually want to make these real panels in their own right, as panels B-G, which may make it easier to read.

**Comment by sjspielman** [comment]
I also think S2B would benefit from this (thumbs up if you agree?) -  https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/figures/compiled_figures/pngs/figure_s2.png

Potentially also the whole of S1, but I think this one is less problematic - https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/figures/compiled_figures/pngs/figure_s1.png

**Comment by jaclyn-taroni** [comment]
S1 seems fine as is to me
