### ISSUE TITLE
Consider adding an adt-by-cell matrix to Figure S2

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-paper-figures#76]
In Figure S2, the current legend text describes that both a gene-by-cell matrix and an adt-by-cell matrix are produced and read into R: https://github.com/AlexsLemonade/ScPCA-manuscript/blob/51b1cdc8f97e738e358ed689e0b863b9faa357b4/content/100.figure-table-legends.md?plain=1#L141-L145

But, [the figure itself](https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/figures/compiled_figures/pngs/figure_s2.png) does not show an adt-by-cell matrix, only the gene-by-cell matrix. 

This issue is meant to a) discuss whether we should add it to the figure, and b) if so, track adding it in. Noting that one reason to not include it is that it may make the figure too crowded, and there's already a lot going on in it.

**Comment by jaclyn-taroni** [comment]
I would say add it, and I don't think we need to discuss it further.

**Comment by sjspielman** [comment]
I think I should be able to add this myself in Illustrator!

**Comment by sjspielman** [comment]
Here's a screenshot of how I've redesigned the figure. Any thoughts before I update pdf/png? @allyhawkins 

![Screenshot 2024-03-06 at 2 52 00 PM](https://github.com/AlexsLemonade/scpca-paper-figures/assets/4701111/5f891185-dec3-460d-8df0-ed8537d60fc5)
